name: Build Docker Image with Kaniko

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker Image with Kaniko
        uses: gcr.io/kaniko-project/executor:latest
        with:
          args: |
            --context . \
            --dockerfile Dockerfile \
            --tar-path /build/image.tar

      - name: Upload Docker Image Tarball
        uses: actions/upload-artifact@v3
        with:
          name: docker-image-tar
          path: /build/image.tar
